### PR TITLE
Make ValidationError class for raising errors

### PR DESCRIPTION
**Pull request by tsuwatch**
Hello, thanks for great gem!
I would like to catch the only `classy_hash` error 🙏

### CODE REVIEW

**Comment by jackcasey** [comment]
I didn't mean to jump on top of this PR with #20,;I just wasn't paying attention, so sorry about that. But after looking at this PR I think #20 is preferable as it doesn't rely on ValidationError being already defined (by Rails I presume? It's not part of vanilla ruby 2.3) and it also has specs.

**Comment by mike-bourgeous** [comment]
@tsuwatch @jackcasey Thanks for the PRs!  A separate exception class is a good idea.  What do you think of the error class for the WIP 0.2.0 version?

The code is here: https://github.com/deseretbook/classy_hash/blob/ntl-validate_full/lib/classy_hash.rb#L14-L37

The PR is here: https://github.com/deseretbook/classy_hash/pull/16

I haven't been able to look at your code yet, but I'll make sure to incorporate your ideas and any feedback you have into version 0.2.0 when I next have time to work on ClassyHash.

**Comment by jackcasey** [comment]
@mike-bourgeous That looks good to me!

**Comment by tsuwatch** [comment]
@mike-bourgeous Looks good, thanks! 🙆

**Pull request closed without merging**
