### PR TITLE
Deep strict validation

### PR DESCRIPTION
**Pull request by NathanielWroblewski**
@mike-bourgeous Adds deep strict validation of schemas to address #9

Open to feedback and changes.

### CODE REVIEW

**Comment by mike-bourgeous** [comment]
@NathanielWroblewski This looks interesting.  I'll have time next week to explore the idea in more detail.

What do you think of the idea of doing away with shallow strict validations and making strictness deep always?  Fewer methods and parameters to pass around that way, and fewer edge cases to test (like making sure shallow checks really are shallow).  Maybe with a minor version bump.

**Comment by NathanielWroblewski** [comment]
I think that makes sense.  My initial expectation was that `validate_strict` would run deeply, so I think making that method deep by default would be less surprising.  

I also share your concern that those changes could break existing implementations, that's why I added this as a separate method.  But if you're considering a version bump with these changes, and as long as the interface supports an option for running shallow validations in strict mode for users who need time to update or do not wish to update, I think that would be a better change.

**Comment by NathanielWroblewski** [comment]
One other concern that may be worth mentioning, is the increasing arity of the validate/validate_strict methods and their order not matching here.  It would perhaps be better to pass a hash of options:
```
ClassyHash.validate_strict(hash, schema, 
  shallow: true,
  verbose: true
)
```

**Comment by mike-bourgeous** [comment]
I'm considering keyword arguments to avoid arity explsion and to avoid `Hash` allocation.

**Comment by mike-bourgeous** [comment]
Superseded by #15

**Comment by NathanielWroblewski** [comment]
Thank you for the great work on this! I really appreciate the rapid progress!  :+1: on the new interface

**Pull request closed without merging**
